name: clcomp21
channels:
  - defaults
dependencies:
  - ca-certificates>=2021.1.1
  - certifi>=2020.12.1
  - pip>=20.0.0
  - python=3.8
  - readline
  - setuptools>=52.0.0
  - sqlite
  - wheel
  - zlib

