dataset: synbols
nb_tasks: 12
known_task_boundaries_at_train_time: true
known_task_boundaries_at_test_time: false
task_labels_at_train_time: true
task_labels_at_test_time: false
monitor_training_performance: true
num_workers: 1
batch_size: 256
wandb:
  project: DER-SSL
  entity: continual-learning
