program: main_sweep.py
method: grid
metric:
  goal: maximize
  name: valid_accuracy
parameters:
  ssl_alpha:
    values: [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27